# config context path to "/" by setting an empty string
server:
  servlet:
    context-path:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  mail:
    host: mail.diggle.tech
    port: 26
    username: qikpaynoreply@diggle.tech
    password: Hklfaokalk.^sfakli5o214
#    smtp:
#      auth: true
#      socketfactory:
#        port: 465
#        class: javax.net.ssl.SSLSocketFactory

#    properties.mail.transport.protocol: smtp
#    properties.mail.smtp.port: 465
    properties:
      mail:
        smtp:
          auth: true
#          starttls:
#            enable: true
#            required: true
          timeout: 30000

        smtps:
          timeout: 30000

#  h2:
#    console:
#      enabled: true

  datasource:
    #    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    #    username: sa
    #    password:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: dbuser
    password: pass123

  jpa:
    #database-platform: org.hibernate.dialect.
    hibernate.ddl-auto: update

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth/login
      refresh: auth/refresh
      register: auth/register

#logging:
#  level:
#    org.springframework:
#      security: DEBUG